### ISSUE TITLE
Move pyver/autover script to pyct?

### ISSUE THREAD

**Issue by ceball** [pyviz-dev/pyct#61]
Seems like a useful script to have available for users (e.g. at bug report time).

https://github.com/pyviz/autover/pull/36

**Comment by ceball** [comment]
Other things that could be useful to report (optionally/if relevant:
  * jupyter lab extensions
  * ...?

Could also consider one or more things from https://github.com/holoviz/panel/pull/825.

**Comment by jbednar** [comment]
I'm strongly in favor of making this information available to all HoloViz users so that they can conveniently report versions in bug reports. I use pyver myself all the time, and wish that everybody did!

**Comment by jbednar** [comment]
And yes, listing jlab extensions is also useful for our debugging purposes.

**Comment by ceball** [comment]
> yes, listing jlab extensions is also useful for our debugging purposes.

Been suffering a lot with this recently myself. You can have all types of extensions installed all over the place (with config easily spanning environments by mistake if you didn't target their installation to the right env). Here are some of the commands I think would be useful to pick from:

## What lab ("frontend") extensions does someone have?

(relevant for e.g. panel)

`jupyter labextension list`

![Screenshot from 2020-05-01 08-28-55](https://user-images.githubusercontent.com/1929/80790233-376d2600-8b86-11ea-8677-f88afc4ece5f.png)

(you can also check the status of a named labextension)

## What server ("backend") extensions does someone have?

(not necessarily relevant for holoviz)

`jupyter serverextension list`

![Screenshot from 2020-05-01 08-35-58](https://user-images.githubusercontent.com/1929/80790469-d560f080-8b86-11ea-9230-2559769ec606.png)

**Comment by ceball** [comment]
Did we agree to add this to the `.github` repo's issue report forms? Pandas does something similar 

![Screenshot from 2020-06-01 08-26-46](https://user-images.githubusercontent.com/1929/83385797-c4074000-a3e1-11ea-89be-65ca601623f7.png)

(`show_versions()`: https://github.com/pandas-dev/pandas/blob/master/pandas/util/_print_versions.py)

**Comment by jbednar** [comment]
Yes, as soon as pyct is released we should ask users to run this command as part of submitting a bug report.

**Comment by ceball** [comment]
Has been done
