### ISSUE TITLE
Failing to report version of command line tools?

### ISSUE THREAD

**Issue by ceball** [pyviz-dev/pyct#88]
pyct does not appear to be reporting correctly on command-line tools.

E.g. below I show `pyct report pyct param python system` not returning anything useful for python.

```
[200911 181348]/tmp$ which python3
/usr/bin/python3
[200911 181349]/tmp$ python3 --version
Python 3.8.2
[200911 181352]/tmp$ python3 -m venv test123
[200911 181406]/tmp$ . test123/bin/activate
(test123) [200911 181423]/tmp$ python -m pip freeze
(test123) [200911 181434]/tmp$ python -m pip install pyct[cmd]
Collecting pyct[cmd]
  Using cached pyct-0.4.7-py2.py3-none-any.whl (15 kB)
Collecting param>=1.7.0
  Using cached param-1.9.3-py2.py3-none-any.whl (70 kB)
Collecting requests; extra == "cmd"
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Processing /home/sefkw/.cache/pip/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c/PyYAML-5.3.1-cp38-cp38-linux_x86_64.whl
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Installing collected packages: param, idna, urllib3, certifi, chardet, requests, pyyaml, pyct
Successfully installed certifi-2020.6.20 chardet-3.0.4 idna-2.10 param-1.9.3 pyct-0.4.7 pyyaml-5.3.1 requests-2.24.0 urllib3-1.25.10
(test123) [200911 181442]/tmp$ python -m pip freeze
certifi==2020.6.20
chardet==3.0.4
idna==2.10
param==1.9.3
pyct==0.4.7
PyYAML==5.3.1
requests==2.24.0
urllib3==1.25.10
(test123) [200911 181453]/tmp$ which python
/tmp/test123/bin/python
(test123) [200911 181513]/tmp$ python --version
Python 3.8.2
(test123) [200911 181515]/tmp$ command -v python
/tmp/test123/bin/python
(test123) [200911 181519]/tmp$ pyct report pyct param python system
pyct=0.4.7                     # /tmp/test123/lib/python3.8/site-packages/pyct
param=1.9.3                    # /tmp/test123/lib/python3.8/site-packages/param
python=unknown                 # not installed in this environment
system=Linux-5.4.0-7642-generic-x86_64-with-glibc2.29 # OS: Linux-5.4.0-7642-generic-x86_64-with-glibc2.29
```

Does it work for other people?

**Comment by ceball** [comment]
@jbednar I'm a bit confused :) In #80 the conclusion seems to be:
  * use `command -v`
  * don't use `shell`

But according to the article I linked there, `command` is something I would expect to come from the shell. And on my linux machine:
```
$ type command
command is a shell builtin
```

On the other hand, I would expect `which` to work ok without shell:
```
$ type which
which is /usr/bin/which
```

I say "work", but I just mean "not fail to run" (as `command` without shell does for me).

Maybe it's all different on mac (if that;s where this work was being done)?

As for getting the right answer (i.e. actually work - to find the same thing that someone would get when they enter a command themselves), in #80 I seem to be arguing that we should be using shell=True. But apparently that did not work for finding stuff.

**Comment by ceball** [comment]
It's not clear to me from

![Screenshot from 2020-09-11 21-02-11](https://user-images.githubusercontent.com/1929/92967977-1db3e780-f472-11ea-808c-81d0c2215af3.png)

what exactly you both tried there.

However, if I assume you tried `subprocess.check_output(['command','-v', package], shell=True)` and/or `subprocess.check_output(['which','-a', package], shell=True)`, i.e. you used a list like that, then it might explain a problem.

https://docs.python.org/3/library/subprocess.html#popen-constructor
> On POSIX with shell=True, the shell defaults to /bin/sh. If args is a string, the string specifies the command to execute through the shell. This means that the string must be formatted exactly as it would be when typed at the shell prompt. This includes, for example, quoting or backslash escaping filenames with spaces in them. If args is a sequence, the first item specifies the command string, and any additional items will be treated as additional arguments to the shell itself.

```python
subprocess.check_output(["command","-v","python"],shell=True)
b''

subprocess.check_output("command -v python",shell=True)
b'/home/sefkw/mc3/envs/tmp/bin/python\n'
```

I think the first form is the same as

```python
subprocess.check_output(["/bin/sh", "-c", "command", "-v", "python"])
b''
```

i.e. it's wrong, and explains why shell=True did not seem to be working.

shell also works for conda, for me:

```python
subprocess.check_output("command -v conda",shell=True)
b'/home/sefkw/mc3/condabin/conda\n'
```

So, I still argue for using shell=True. And `command` seems like a good choice.

What do you think? And could you verify on mac (and whatever weird shell you use ;) )?

**Comment by jbednar** [comment]
I hadn't been able to test it because pyct wouldn't install, but it looks like that's due to setting `channel_priority: strict` in my .condarc, which was to get some other behavior earlier in a different case.  Changing channel_priority to `false` lets me install pyct, at which point it does seem to work on a Mac:

```
$ pyct report pyct param python conda system
pyct=0.4.7                     # /Users/jbednar/miniconda3/envs/holoviz-tutorial/lib/python3.7/site-packages/pyct
param=1.9.3                    # /Users/jbednar/miniconda3/envs/holoviz-tutorial/lib/python3.7/site-packages/param
python=3.7.7                   # /Users/jbednar/miniconda3/envs/holoviz-tutorial/bin/python
conda=4.8.4                    # /Users/jbednar/bin/conda
system=Darwin-19.6.0           # OS: Darwin-19.6.0-x86_64-i386-64bit
```

What I think you are proposing also seems to work:

```
$ python
Python 3.7.7 (default, Mar 23 2020, 17:31:31) 
>>> import subprocess
>>> subprocess.check_output("command -v conda",shell=True)
b'/Users/jbednar/bin/conda\n'
>>> subprocess.check_output("command -v python",shell=True)
b'/Users/jbednar/miniconda3/envs/holoviz-tutorial/bin/python\n'
```

So I'm guessing that if you make the changes you proposed, it will work on both Mac and your Linux system. Seems like an improvement, then!

Note that `system` doesn't look like it's working well for you:

```
system=Linux-5.4.0-7642-generic-x86_64-with-glibc2.10 # OS: Linux-5.4.0-7642-generic-x86_64-with-debian-bullseye-sid
```

It would be nice if that looked more like:

```
system=Linux-5.4.0               # OS: Linux-5.4.0-7642-generic-x86_64-with-glibc2.10-with-debian-bullseye-sid
```

I.e., it was _supposed_ to have short name at first and then more detail. Not sure why the code achieves that on Mac but not this version of Linux, particularly in that the "longer" one has _less_ information than the "shorter" one in some ways.

**Comment by ceball** [comment]
Thanks for checking on mac.

> I hadn't been able to test it because pyct wouldn't install

Could that be related to this pin? https://github.com/holoviz/datashader/blob/master/setup.py#L25 (https://github.com/holoviz/datashader/pull/960)

> it does seem to work on a Mac

I guess on mac `command` must also be available outside the shell, then?

> system doesn't look like it's working well for you

I wondered about that, but wasn't sure what it was supposed to look like :)

> Setting terse to true causes the function to return only the absolute minimum information needed to identify the platform.

Seems tricky :)

```
>>> platform.platform()
'Linux-5.4.0-7642-generic-x86_64-with-debian-bullseye-sid'
>>> platform.platform(terse=True)
'Linux-5.4.0-7642-generic-x86_64-with-glibc2.10'
>>> platform.system()
'Linux'
>>> platform.uname()
uname_result(system='Linux', node='mikan', release='5.4.0-7642-generic', version='#46~1598628707~20.04~040157c-Ubuntu SMP Fri Aug 28 18:02:16 UTC ', machine='x86_64', processor='x86_64')
>>> platform.libc_ver()
('glibc', '2.10')```
